---
title: "hw04"
author: "Bartell Lin"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("../code/archive_functions.R")
source("../code/regex_functions.R")
```

```{r}
raw_data <- read_archive("stringr")
clean_data <- clean_archive(raw_data)
plot_archive(clean_data)
ggsave("../images/stingr.png")
```

```{r}
raw_gg <- read_archive("ggplot2")
clean_gg <- clean_archive(raw_gg)
write.csv(clean_gg, "../data/ggplot2_archive.csv")

raw_xml <- read_archive("XML")
clean_xml <- clean_archive(raw_xml)
write.csv(clean_xml, "../data/XML_archive.csv")

raw_knitr <- read_archive("knitr")
clean_knitr <- clean_archive(raw_knitr)
write.csv(clean_knitr, "../data/knitr_archive.csv")

raw_dp <- read_archive("dplyr")
clean_dp <- clean_archive(raw_dp)
write.csv(clean_dp, "../data/dplyr_archive.csv")
```

```{r}
ggplot(rbind(clean_gg, clean_dp, clean_knitr, clean_xml)) + geom_step(aes(date, size, color = name))
ggsave("../images/overlay.png")
```

```{r}
ggplot(rbind(clean_gg, clean_dp, clean_knitr, clean_xml)) + geom_step(aes(date, size, color = name)) + facet_wrap(~name)
ggsave("../images/facet.png")
```


```{r}
split_char("Go Bears!")
split_char("Expecto Patronum")
```

```{r}
vec <- c(split_char("Go Bears!"))
num_vowels(vec)
```

```{r}
count_vowels("The quick brown fox jumps over the lazy dog")
count_vowels("THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG")
```

```{r}
reverse_chars("gattaca")
reverse_chars("Lumox Maxima")
```


```{r}
reverse_words("sentence! this reverse")
reverse_words("string")
```

```{r}
dat <- read.csv('../data/text-emotion.csv', stringsAsFactors = FALSE)
```

```{r}
count <- c()
for (i in dat['content']) {
  count <- c(count, str_length(i))
}
summary(count)
hist(count, breaks= seq(0,170,5))
```

```{r}
ten <- c()
n <- length(dat['content'][,])
counts <- c()
for (i in 1:1000) {
  spl <- str_split(dat['content'][, 1], " ")[[i]]
  spl <- grepl("^@\\w{1}[[:alnum:]_\\]+$", spl)
  counts <- c(counts, sum(spl))
  if (sum(spl) == 10) {
    ten <- c(dat['content'][, 1][[i]])
  }
}
```
```{r}
for (i in 10001:2000) {
  spl <- str_split(dat['content'][, 1], " ")[[i]]
  spl <- grepl("^@\\w{1}[[:alnum:]_\\]+$", spl)
  counts <- c(counts, sum(spl))
  if (sum(spl) == 10) {
    ten <- c(dat['content'][, 1][[i]])
  }
}
```
```{r}
for (i in 2001:3000) {
  spl <- str_split(dat['content'][, 1], " ")[[i]]
  spl <- grepl("^@\\w{1}[[:alnum:]_\\]+$", spl)
  counts <- c(counts, sum(spl))
  if (sum(spl) == 10) {
    ten <- c(dat['content'][, 1][[i]])
  }
}
```
```{r}
for (i in 3001:4000) {
  spl <- str_split(dat['content'][, 1], " ")[[i]]
  spl <- grepl("^@\\w{1}[[:alnum:]_\\]+$", spl)
  counts <- c(counts, sum(spl))
  if (sum(spl) == 10) {
    ten <- c(dat['content'][, 1][[i]])
  }
}
```

```{r}
hist(counts)
```

```{r}
ten
```


```{r}

```

```{r}
n <- length(dat['content'][,])
len <- c()
hash <- c()
for (i in 1:1000) {
  spl <- str_split(dat['content'][, 1], " ")[[i]]
  s <- grepl("^#\\w{1}[[:alpha:]]+[[:alnum:]]+$", spl)
  hash <- c(counts, sum(s))
  len <- c(len, str_length(spl[s]) - 1)
}
```
```{r}
for (i in 1001:2000) {
  spl <- str_split(dat['content'][, 1], " ")[[i]]
  s <- grepl("^#\\w{1}[[:alpha:]]+[[:alnum:]]+$", spl)
  hash <- c(counts, sum(s))
  len <- c(len, str_length(spl[s]) - 1)
}
```
```{r}
for (i in 2001:3000) {
  spl <- str_split(dat['content'][, 1], " ")[[i]]
  s <- grepl("^#\\w{1}[[:alpha:]]+[[:alnum:]]+$", spl)
  hash <- c(counts, sum(s))
  len <- c(len, str_length(spl[s]) - 1)
}
```
```{r}
for (i in 3001:4000) {
  spl <- str_split(dat['content'][, 1], " ")[[i]]
  s <- grepl("^#\\w{1}[[:alpha:]]+[[:alnum:]]+$", spl)
  hash <- c(counts, sum(s))
  len <- c(len, str_length(spl[s]) - 1)
}
```


```{r}
hist(hash)
```

```{r}
mean(len)
unique(len)[which.max(tabulate(match(len, unique(len))))]
```

