---
title: "hw02"
author: Bartell lin
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../images/")
```

```{r}
library(dplyr)
library(ggplot2)
```

```{r}
dat <- read.csv("../data/shots-data.csv")
dat %>% 
  group_by(name) %>% 
  summarise(total = n()) %>% 
  arrange(desc(total))
```

```{r}
effective <- dat 
t <- count(effective, name, total = n(), bool = shot_made_flag == "made shot")
t <- t[t$bool == TRUE, ]
dat %>%
  group_by(name) %>%
  summarise(total = n()) %>%
  mutate("made" = t$n, perc_made = made/total) %>%
  arrange(desc(perc_made))
```
```{r}
two <- dat[dat$shot_type == "2PT Field Goal", ]
x <- count(two, name, total = n(), bool = shot_made_flag == "made shot")
x <- x[x$bool == TRUE, ]
dat %>%
  group_by(name) %>%
  summarise(total = n()) %>%
  mutate("made" = x$n, perc_made = made/total) %>%
  arrange(desc(perc_made))

```


```{r}
three <- dat[dat$shot_type == "3PT Field Goal", ]
y <- count(three, name, total = n(), bool = shot_made_flag == "made shot")
y <- y[y$bool == TRUE, ]
dat %>%
  group_by(name) %>%
  summarise(total = n()) %>%
  mutate("made" = y$n, perc_made = made/total) %>%
  arrange(desc(perc_made))
```


```{r}
whole <- split <- dat %>% group_by(shot_distance) %>% summarise(total = n())
split <- dat %>% group_by(shot_distance, bool = as.numeric(shot_made_flag == "made shot"))
split <- count(split)
split$n[split$bool == 0] <- 0
ag <- aggregate(n ~ shot_distance, data = split, sum)

tbl <- mutate(ag, made_shot_prop = ag[[2]]/whole[[2]]) %>%
  select(c(1,3))
tbl
```

```{r}
ggplot(tbl, aes(x = shot_distance, y = made_shot_prop)) + geom_point()
```

I can see that the shorter the distance, the higher the  percentage that the shot makes it in. After about 35 feet, the chances of getting the ball in are basically null. There is however, one outlier. Distances of 1, 2, and 3 feet have percentages over 50%. There are a couple around 20 feet that make the threshold as well. 



```{r}
gdat <- dat %>%
  group_by(minute, name) %>%
  count(minute, name)


ggplot(gdat, aes(x= minute, y= n)) + geom_rect(xmin = 0, xmax= 12, ymin = 0, ymax= 100, fill = "grey") + geom_rect(xmin = 24, xmax= 36, ymin = 0, ymax= 100, fill = "grey") + geom_point() + geom_path() + facet_wrap(~name) + theme_minimal() + scale_x_continuous(limits = c(0, 48)) + ylab("total number of shots")
```
